### ISSUE TITLE
Consider using Function instead of eval()

### ISSUE THREAD

**Issue by sanity** [kwebio/core#11]
Use of eval() is discouraged - see [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#Don't_use_eval_needlessly!).

Determine whether there is a better alternative, such as [Function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function).

**Comment by Valerson** [comment]
As a note, per Kyle Simpson (getify)'s [book](https://github.com/getify/You-Dont-Know-JS/blob/master/scope%20%26%20closures/ch2.md):

> 
> The `new Function(..)` function constructor similarly takes a string of code in its last argument to turn into a dynamically-generated function (the first argument(s), if any, are the named parameters for the new function). This function-constructor syntax is slightly safer than eval(..), but it should still be avoided in your code.
> 
> The use-cases for dynamically generating code inside your program are incredibly rare, as the performance degradations are almost never worth the capability.

This _could_ be one of those use cases, provided that the code we're passing is minimal. The main issue with both eval() and new Function() is that the code passed through it _cannot_ be optimized by the JS engine. Complex code is likely to execute poorly/slowly, which defeats the purpose of your engine being speedy in all other regards.

---

I'm a JS guy attempting to learn Kotlin.. I'll see what I can do as I learn the kt side of things.

**Comment by sanity** [comment]
Hi, thank you for the feedback.

We are aware that use of `eval` and `Function` are slow, as a result Kweb avoids using it except for relatively rare instruction types.

It does this by using pre-defined message types for common instructions, you can see the server-side of this [here](https://github.com/kwebio/core/blob/master/src/main/kotlin/io/kweb/Kweb.kt#L469) and the client side [here](https://github.com/kwebio/core/blob/master/src/main/resources/io/kweb/kweb_bootstrap.html#L71).

This should mean that calls to `eval` are relatively infrequent.  If it is being called frequently for you then let me know, I might be able to solve the problem with a few new pre-defined message types.
