### ISSUE TITLE
Kweb.io broken example links

### ISSUE THREAD

**Issue by arocnies** [kwebio/core#27]
There appear to be some broken links on the [kweb.io](kweb.io) site. I didn't see a repo for the site--is this the right place for the issue?

Broken links:

On the [More examples](http://kweb.io/use/more-examples.html) page:
- "See other demos of Kweb’s capabilities **here**." https://github.com/sanity/kweb/tree/master/src/main/kotlin/com/github/sanity/kweb/demos
Should this be changed to: https://github.com/kwebio/kweb-demo?

- "**This demo** illustrates Kweb’s powerful asynchronous features..." https://github.com/sanity/kweb/blob/master/src/main/kotlin/com/github/sanity/kweb/demos/async/async.kt

**Comment by sanity** [comment]
Thank you, fixed!

(BTW - the website is hosted here: https://github.com/kwebio/kwebio.github.io - I should note that somewhere)
