### ISSUE TITLE
Investigate use of a Virtual Dom

### ISSUE THREAD

**Issue by sanity** [kwebio/core#31]
Virtual DOMs are increasingly popular for speeding up browser-side rendering.  We should investigate whether Kweb can take advantage of a virtual DOM for similar benefit.

This one looks interesting https://github.com/snabbdom/snabbdom

**Comment by ammelto** [comment]
Hey, I'd be interested in taking this on. I'm using kweb in a production application and a virtual dom is kind of necessary for this. Have you thought at all about how to implement this? I was thinking we could write our own vnodes and do the diff on the server then just send down the diff to the client. Most out of box solutions for this I don't think will fit nicely into kweb so we will likely have to roll our own.

**Comment by sanity** [comment]
@ammelto I'm not sure whether I'm more delighted or terrified that you're using kweb in a production application ;)  I'm very curious to learn more about how you're using it, depending on how much you can tell me.

I have actually done quite a bit of thinking related to this, and have implemented some potentially relevant stuff like caching non-visible DOM components such that they render instantly.  There is a lot more that could be done in this direction - but I'd need to learn more about the needs motivating this for you.  Can you elaborate a bit?

**Comment by sanity** [comment]
I just pushed it, check out the new `cacheOnClient` parameter for `render`.  It hides the DOM on the  client so it's ready to go when needed again - even stays in sync with state while it's hidden.

In my playing around - the difference is very noticeable, the render is instant.

**Comment by ammelto** [comment]
Sorry about the late reply, I was flying home from LA.

I'll check it out. Do you have a slack/gitter or something setup for this? I'm more than happy to talk about what I'm using kweb for but I don't want to clutter up the issues section of this repo haha.

**Comment by sanity** [comment]
Absolutely, you can join https://gitter.im/kwebio/Lobby

Look forward to discussing there!

**Comment by sanity** [comment]
Closing, I think cacheOnClient may take care of this.
