### ISSUE TITLE
Pre-load DOM instructions to fire instantly on an event

### ISSUE THREAD

**Issue by sanity** [kwebio/core#35]
Currently when a listener is attached to an event, when the event fires a message is sent from client to server which responds by executing a callback, that may send further instructions to the client.  This may incur a noticeable delay.

We should "pre-load" instructions to the client which execute without delay until some server communication is required, and only then should the client wait on a server message.

It's possible that this could be achieved in a mostly programmer-transparent way through coroutines, I can elaborate if anyone is interested.

**Comment by kosiakk** [comment]
I think, if the specific Kotlin callback function can be compiled to JS and sent to the client - it should be.

**Comment by sanity** [comment]
@kosiakk That is a much better solution than I had in mind **if** it actually works :)  Do you think it would?

**Comment by sanity** [comment]
Fixed a few weeks ago, sorry for not closing the issue.  In addition to `Element.on.click {}`there is now `Element.onImmediate.click {}`.  Any dom-modifying instructions will be pre-loaded to the client for immediate execution on the event (before any server round-trip).

Relevant code: https://github.com/kwebio/core/blob/master/src/main/kotlin/io/kweb/dom/element/events/ONImmediateReceiver.kt
