### ISSUE TITLE
Provide fallback message when JavaScript is not available

### ISSUE THREAD

**Issue by sanity** [kwebio/core#45]
Kweb should provide a simple but friendly message to the user if they attempt to visit the site in a browser without JavaScript.

**Comment by ethanmdavidson** [comment]
I can take care of this. Did you have something in mind besides a simple `<noscript>` tag?

**Comment by sanity** [comment]
Sorry I missed this @ethanmdavidson, but yes - that's exactly what I had in mind.  Thank you!
