### ISSUE TITLE
Fomantic plugin adds non-existing stylesheet/src link to fomantic.min.css/js instead of semantic.min.css/js

### ISSUE THREAD

**Issue by lwiddershoven** [kwebio/core#54]
Using kweb 0.4.8 with the fomantic plugin as referenced by the documentation does not work for me.

It seems that the plugin creates a non-resolvable link like https://cdn.jsdelivr.net/npm/fomantic-ui@2.7.4/dist/fomantic.min.css´ in FomanticUIPlugin.kt .

The Fomantic documentation however refers to semantic.
https://fomantic-ui.com/introduction/getting-started.html : 
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/fomantic-ui@2.7.4/dist/semantic.min.css">
<script src="https://cdn.jsdelivr.net/npm/fomantic-ui@2.7.4/dist/semantic.min.js"></script>

**Comment by sanity** [comment]
I've just deployed Kweb 0.4.10, in which I've attempted to correct the url, would appreciate testers.

**Comment by sanity** [comment]
Oh, you're also welcome to submit a pull request if you think any further changes would be beneficial.

**Comment by lwiddershoven** [comment]
Doesn't work for me due to typo in FomanticUIPlugin:
 fixed line to: <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/fomantic-ui@2.7.4/dist/semantic.min.css">

(it was somantic, which is wrong:)

Also, it seems that the dependency groupId was changed from com.github to io.kweb ; is that an artifact of the local build or has it actually been changed? It was kind of confusing.

I'll have a look at the pull request thing.

**Comment by sanity** [comment]
Oh crap, sorry about that, would you mind trying 0.4.11?  This is what I get for pushing out fixes late at night.

**Comment by sanity** [comment]
@lwiddershoven I've also updated http://demo.kweb.io:7659 so you can see it in action :)

Closing but please reopen if you continue to have issues.

**Comment by sanity** [comment]
Oh, re: dependency group id, yes - I changed that for consistency, did this cause problems?

**Comment by sanity** [comment]
@lwiddershoven Can you confirm closed?
