### ISSUE TITLE
JPMS/Jigsaw Support

### ISSUE THREAD

**Issue by alkoclick** [kwebio/core#61]
Java 9+ versions ship with the module system and it's becoming more and more common, having just crossed 1000 maven projects fully supporting it (correctly).

Is there a plan for kweb to support JPMS modules? There are definitely quite a few collisions when attempting to use it that way out of the box

**Comment by alkoclick** [comment]
I am working with Gradle and currently having success building using the [Java Modularity Gradle plugin](https://github.com/java9-modularity/gradle-modules-plugin) and the following configuration (see [here](https://github.com/java9-modularity/gradle-modules-plugin#patching-modules-to-prevent-split-packages) for an explanation of what this does)

```groovy
patchModules.config = [
        "ktor.websockets=ktor-http-cio-jvm-1.2.0.jar",
        "ktor.utils.jvm=ktor-server-core-1.2.0.jar"
]
```

**Comment by alkoclick** [comment]
Update: The above module patch config doesn't fully work and the java modularity plugin has some trouble handling multiple jar patches, I've filed [an issue](https://github.com/java9-modularity/gradle-modules-plugin/issues/93) with them

**Comment by ethanmdavidson** [comment]
I've only read about JPMS and haven't done anything with it yet, so I might be way off here, but won't JPMS support mean we can only target Java 9+? I think JPMS is the way to go but most of the world is still on Java 8 so I think we want to maintain compatibility until 11 sees wide adoption. Of course, kweb is still very "cutting edge" and doesn't have a huge user base to support, so maybe we shouldn't worry about it. I guess that's a call for @sanity to make.

**Comment by alkoclick** [comment]
Actually not. You don't need first class support at any rate - just fix the package collisions I've outlined above and people will be able to use your artifacts with automatic modules. Besides changing the package names, you don't need to take any other action!

I understand changing these names is a simple, but big change. However it will immediately unlock all Java 9+ consumers for your framework and it is going to be needed anyway if you intend to ever support modules

**Comment by sanity** [comment]
@alkoclick Happy to apply the changes, although as you're more familiar with the module system than I am - care to submit a pull request? ;)

**Comment by sanity** [comment]
Hmm, I guess I don't understand the module system.

Is the issue here that two different versions of Ktor are being pulled in?

**Comment by alkoclick** [comment]
Not the different versions of ktor, but rather, the fact that the same package exists in multiple jars, which messes with the autogenerated modules that would otherwise work.

[Nikolai probably explains it better](https://blog.codefx.org/java/java-9-migration-guide/#Split-Packages)

I have however made a mistake - I was under the impression that the ktor jars were produced by you, which is not the case. This is strictly a ktor issue, and I see there [it is already filed and looking to be on the roadmap](https://github.com/ktorio/ktor/issues/1137)

**Comment by alkoclick** [comment]
Actually I got an idea for a fix that could perhaps work in the meantime, I'll try it over the weekend and let you know if I can make it work

**Comment by sanity** [comment]
Sounds good, thank you!

**Comment by alkoclick** [comment]
This may work as a workaround temporarily, linking here so it won't get lost: https://github.com/java9-modularity/gradle-modules-plugin/issues/93
